### ISSUE TITLE
Other version please

### ISSUE THREAD

**Issue by Walking-stone** [FXCourel/Copper-Rails#3]
This is a very good mod, can you port it to other Minecraft versions? For example, 1.20.1 and 1.18.2. Thank you very much:)

**Comment by FXCourel** [comment]
I will try to do this tomorrow, this should be rather easy I guess, there was almost no change in minecart system. Have you tried to put the mod in older versions ? There are even possibilities that it works.
Anyway I’m glad to see you appreciate this mod.

**Comment by FXCourel** [comment]
Done (took longer than expected)
